workflows:
  build-android-apk:
    name: Build Android APK
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      flutter: stable
    scripts:
      - name: Set up environment
        script: |
          echo "Using Java 17 and Android SDK from Codemagic environment"
      - name: Build debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com  # можешь удалить
