workflows:
  build-android-apk:
    name: Build Android APK
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      android:
        image: latest
    scripts:
      - name: Set up environment
        script: |
          echo "Using Java 17 and latest Android SDK"
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com  # можно удалить, если не нужно уведомление
